name: GYG Scraper Pipeline (Matriz Paralela)

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * 1'

jobs:
  # ==========================================
  # JOB 1: Extraer Sitemaps y Limpiar BigQuery
  # ==========================================
  extract_sitemaps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Autenticar en Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Instalar dependencias
        run: pip install pandas requests google-cloud-bigquery[pandas] pyarrow db-dtypes

      - name: Ejecutar Script de Sitemaps y Preparar BQ
        run: python gyg/gyg_sitemap_github.py

      - name: Subir CSVs de todos los países como Artefactos
        uses: actions/upload-artifact@v4
        with:
          name: sitemaps_data
          path: tours_urls_*.csv
          retention-days: 1

  # ==========================================
  # JOB 2: Scraper de Precios en Paralelo (13 Servidores)
  # ==========================================
  extract_prices_and_upload:
    needs: extract_sitemaps
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Si un país falla, los demás continúan trabajando
      matrix:
        # Los nombres exactos que usaremos para separar los archivos
        country: [Brasil, Mexico, Argentina, Chile, Colombia, Peru, Costa_Rica, Panama, Ecuador, Paraguay, Uruguay, Bolivia, Republica_Dominicana]
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Descargar CSVs del Job anterior
        uses: actions/download-artifact@v4
        with:
          name: sitemaps_data

      - name: Autenticar en Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Instalar dependencias
        run: pip install pandas requests beautifulsoup4 google-cloud-bigquery[pandas] pyarrow db-dtypes

      - name: Ejecutar Scraper para ${{ matrix.country }}
        # Pasamos el nombre del país como argumento al script de Python
        run: python gyg/gyg_precios_github.py ${{ matrix.country }}